export const compliments: string[] = [
    "You look nice today",
    "I love that shirt!",
    "I hope you have the best sleep tonight!",
    "Wow, have you been working out?",
    "People really admire how hard you work!",
    "You always brighten the room when you walk in!",
    "I love your laugh!",
    "Someone's day is better because of you!",
    "You have great taste in things, seriously, you always pick the good stuff!",
    "You’re the kind of person people feel lucky to know!",
    "That smile? 10/10, would recommend.",
    "You make hard things look easy (even if they aren’t).",
    "Your laugh could brighten up a whole room!",
    "You’re better at this whole being a human thing than you give yourself credit for!",
    "Someone out there is having a better day just because you exist!",
    "You’re really, really good at caring about people, it shows!",
    "You’re way cooler than you think you are right now.",
    "You make people feel comfortable right away!",
    "You notice little details most people miss :)",
    "You’re the kind of person who makes other people want to try harder (in a good way).",
    "You have main character energy, in the best way!",
    "Your taste in music, books, or shows is probably immaculate.",
    "The world's a better place with you in it!",
    "You make people feel seen without even trying.",
    "Your kindness is the kind that sticks with people for years!",
    "You’re secretly someone’s favourite person!",
    "You have a way of making tough days feel easier for others!",
    "Your laugh is contagious in the best way.",
    "You’re better at listening than most people even try to be.",
    "You’d be a great main character in someone’s favourite story.",
    "You make the people around you feel safe.",
    "You’re the reason someone still believes in good people!",
    "You have a great sense of humor!",
    "You’re more thoughtful than you realize.",
    "The world feels a little lighter when you’re around.",
    "You’re exactly the kind of person people hope to meet.",
    "You have a way of making ordinary things feel special.",
    "Your smile could make a stranger’s whole day better!",
    "You make being yourself look really good.",
    "You’re proof that good people still exist.",
    "You’re someone who makes life feel more fun just by being in it.",
    "You give off the kind of energy people want to be around.",
    "You’re a bright spot in a lot of people’s memories.",
    "You have the kind of laugh that makes people laugh with you.",
    "You’re cooler than you think you are.",
    "You’re someone others feel lucky to call a friend.",
    "Your vibe makes stressful moments feel calmer.",
    "You’re better at making people smile than you think.",
    "You bring out the best in the people you care about.",
    "You’re someone who makes other people feel important.",
    "You’re the kind of person people talk about fondly when you’re not around.",
    "You’re a lot more charming than you realize.",
    "You have a naturally comforting presence.",
    "Your happiness is the kind that’s hard not to catch.",
    "You're unstoppable!",
    "You're very brave! ᕙ(  •̀ ᗜ •́  )ᕗ",
    "Never doubt that one person can make a difference - from the biggest person to the smallest hobbit. You are important!",
    "You're never lost - you're exploring.",
    "Your smile is contagious.",
    "Your smile makes the sun look dull.",
    "You are much more beautiful than you think. :)",
    "You make people feel like hugs and rainbows and puppies and chocolate chip cookies.",
    "You're a kind person who can make other people feel seen.",
    "You are strong!",
    "You are loved.",
    "You are so capable of anything you set your mind to.",
    "Lots of people find you fun to be around.",
    "People gossip about you behind your back... talking about how great you are.",
    "You seem like you'd be awesome to dance with!",
    "As long as you try and you care, you're already a winner.",
    "You're a cutie.",
    "You are strong and resilient.",
    "You bring a little sparkle with you everywhere you go.",
    "You smell great!",
    "Your presence fills the room!",
    "You are enough. You are amazing. You are worth every breath of air you breathe. You can get through this, internet person. You matter. :)",
    "You're pretty awesome. You're pretty, you're awesome, and pretty awesome! And awesomely pretty.",
    "Thank you for all you do. You matter!",
    "You're cool.",
    "Memories are made when a person is happy, and you've helped create a lot of happy memories.",
    "You are stronger than you know!",
    "Someone thought about you today and smiled! <3",
    "Don't overthink too much - you can do it!",
    "There are people taking your advice that you don't even know about.",
    "Someone looked at you today and thought you were really cool."
];


export const generateText: string[] = [
  "Tell me something nice!",
  "Tell me something nice!",
  "One more, please!",
  "One more, please!",
  "Another one, please!"
]
