export const compliments: string[] = [
    "You look nice today",
    "I love that shirt!",
    "I hope you have the best sleep tonight!",
    "Wow, have you been working out?",
    "People really admire how hard you work!",
    "You always brighten the room when you walk in!",
    "I love your laugh!",
    "Someone's day is better because of you!",
    "You have great taste in things, seriously, you always pick the good stuff!",
    "You’re the kind of person people feel lucky to know!",
    "That smile? 10/10, would recommend.",
    "You make hard things look easy (even if they aren’t).",
    "Your laugh could brighten up a whole room!",
    "You’re better at this whole being a human thing than you give yourself credit for!",
    "Someone out there is having a better day just because you exist!",
    "You’re really, really good at caring about people, it shows!",
    "You’re way cooler than you think you are right now.",
    "You make people feel comfortable right away!",
    "You notice little details most people miss :)",
    "You’re the kind of person who makes other people want to try harder (in a good way).",
    "You have main character energy, in the best way!",
    "Your taste in music, books, or shows is probably immaculate.",
    "The world's a better place with you in it!",
    "You make people feel seen without even trying.",
    "Your kindness is the kind that sticks with people for years!",
    "You’re secretly someone’s favorite person!",
    "You have a way of making tough days feel easier for others!",
    "Your laugh is contagious in the best way.",
    "You’re better at listening than most people even try to be.",
    "You’d be a great main character in someone’s favorite story.",
    "You make the people around you feel safe.",
    "You’re the reason someone still believes in good people!",
    "You have a great sense of humor!",
    "You’re more thoughtful than you realize.",
    "The world feels a little lighter when you’re around.",
    "You’re exactly the kind of person people hope to meet.",
    "You have a way of making ordinary things feel special.",
    "Your smile could make a stranger’s whole day better!",
    "You make being yourself look really good.",
    "You’re proof that good people still exist.",
    "You’re someone who makes life feel more fun just by being in it.",
    "You give off the kind of energy people want to be around.",
    "You’re a bright spot in a lot of people’s memories.",
    "You have the kind of laugh that makes people laugh with you.",
    "You’re cooler than you think you are.",
    "You’re someone others feel lucky to call a friend.",
    "Your vibe makes stressful moments feel calmer.",
    "You’re better at making people smile than you think.",
    "You bring out the best in the people you care about.",
    "You’re someone who makes other people feel important.",
    "You’re the kind of person people talk about fondly when you’re not around.",
    "You’re a lot more charming than you realize.",
    "You have a naturally comforting presence.",
    "Your happiness is the kind that’s hard not to catch."
];


export const generateText: string[] = [
  "Tell me something nice!",
  "Tell me something nice!",
  "One more, please!",
  "One more, please!",
  "Another one, please!"
]
